# Basic Site Settings
title: "Uyen Vu | Full-Stack Developer"
description: "Personal Portfolio, Projects, and Resume"
url: "https://uynvu078.github.io"
baseurl: ""
repository: "uynvu078/uynvu078.github.io"

# Author Settings
author:
  name: "Uyen Vu"
  bio: "Software Developer passionate about creating scalable and user-friendly applications."
  location: "Houston, TX"
  email: "uyenvu315@gmail.com"
  avatar: "profile.png"
  github: "uynvu078"
  linkedin: "https://www.linkedin.com/in/uyen-vu-sf8358/"

# Build Settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO and Analytics
google_analytics: G-6T0G8L96M1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Output settings
permalink: /:categories/:title/
timezone: America/Chicago

# Exclude these files from the final site
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - tmp
  - .sass-cache
  - .jekyll-cache
  - package.json
  - yarn.lock
  - Dockerfile

# Defaults for all pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      stylesheet: assets/css/style.css
